import json
import logging

from diverge.agents.base import DivergeAgentNode
from diverge.agents.utils.agent_utils import (
    build_instrument_context,
    get_evidence_rules_instruction,
    get_language_instruction,
    get_research_note_style_instruction,
    get_trade_feedback_message,
)
from diverge.runtime.messages import AdkPrompt

logger = logging.getLogger(__name__)


def _error_status_code(error: BaseException) -> int | None:
    status_code = getattr(error, "status_code", None)
    if isinstance(status_code, int):
        return status_code

    response = getattr(error, "response", None)
    response_status = getattr(response, "status_code", None)
    if isinstance(response_status, int):
        return response_status

    return None


def _is_transient_llm_error(error: BaseException) -> bool:
    status_code = _error_status_code(error)
    if status_code in {408, 409, 429, 500, 502, 503, 504}:
        return True

    message = str(error).lower()
    return (
        "gateway time-out" in message
        or "gateway timeout" in message
        or "connection error" in message
        or "connection reset" in message
        or "unexpected_eof_while_reading" in message
        or "eof occurred in violation of protocol" in message
        or "timed out" in message
        or "timeout" in message
        or "temporarily unavailable" in message
    )


def _json_block(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _format_transient_llm_warning(error: BaseException) -> dict[str, str]:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    return {
        "stage": "Portfolio Manager",
        "kind": "transient_llm_error",
        "message": (
            "Portfolio Manager used a conservative fallback because the LLM request "
            f"failed with a transient connection error: {error_note}"
        ),
    }


def _build_fallback_portfolio_decision(
    *, instrument_context: str, error: BaseException
) -> str:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    summary = (
        "Portfolio Manager LLM request failed before producing a final ruling; "
        "treat this as a low-confidence no-action fallback and review the full report."
    )
    thesis = (
        "The analyst, trader, and risk debate sections were generated, but the final "
        "Portfolio Manager synthesis could not be completed because the model gateway "
        "returned a transient connection error."
    )

    highlights = {
        "category": "portfolio_decision",
        "signal": "HOLD",
        "signal_confidence": "low",
        "summary": summary,
        "final_decision": "HOLD",
        "decision_basis": "Final Portfolio Manager synthesis was unavailable due to an upstream transient LLM connection failure.",
        "strategic_actions": [
            {
                "action": "Review the full report manually before taking action.",
                "priority": "immediate",
            }
        ],
        "risk_warnings": [
            "Final portfolio ruling was generated by fallback logic.",
            "LLM gateway connection failure may have prevented risk adjustments from being synthesized.",
        ],
    }
    decision_card = {
        "card_version": "1.2",
        "rating": "HOLD",
        "action": "NO_ACTION",
        "confidence": "low",
        "conviction_score": 0,
        "time_horizon": "Manual review required",
        "one_line_summary": summary,
        "thesis": thesis,
        "price_plan": {
            "current_price": None,
            "entry_zone": None,
            "add_condition": None,
            "stop_loss": None,
            "take_profit": None,
            "invalidation": [
                "A reliable Portfolio Manager final ruling is regenerated successfully."
            ],
            "risk_reward_note": "No risk/reward plan was generated because final synthesis timed out.",
        },
        "suggested_position": None,
        "key_reasons": [
            {
                "pillar": "portfolio",
                "point": "Fallback final ruling",
                "evidence": "The Portfolio Manager LLM call failed after retryable transient connection handling.",
                "strength": "weak",
            }
        ],
        "key_risks": [
            "No authoritative final Portfolio Manager synthesis is available.",
            "The user must inspect the analyst and risk debate sections manually.",
        ],
        "catalysts": [],
        "watch_items": [
            "Regenerate the Portfolio Manager decision when the LLM gateway connection is stable."
        ],
        "data_quality_notes": [
            "Fallback decision generated after transient LLM connection failure.",
            f"Upstream error: {error_note}",
        ],
        "trade_readiness": "DATA_INSUFFICIENT",
        "trade_readiness_reason": "Structured Portfolio Manager synthesis was unavailable, so no execution call is reliable.",
        "blocking_items": ["Regenerate the Portfolio Manager decision."],
        "data_quality_level": "insufficient",
        "data_quality_summary": "The final decision is a fallback because Portfolio Manager synthesis failed.",
        "why_not": {
            "why_not_more_bullish": "The final Portfolio Manager synthesis did not complete.",
            "why_not_more_bearish": "The completed analyst sections still need manual review before a stronger negative ruling.",
            "why_not_act_now": "The structured final ruling is unavailable and should be regenerated first.",
        },
        "action_playbook": {
            "do_now": ["Review the full report manually before taking action."],
            "trigger_to_act": [
                "Regenerate the Portfolio Manager decision successfully."
            ],
            "invalidation": [
                "A reliable Portfolio Manager final ruling is regenerated successfully."
            ],
            "execution_notes": ["No trading action should rely on this fallback card."],
        },
        "position_guidance": {
            "suggested_exposure": "No new risk exposure should be based on this fallback card.",
            "max_exposure": None,
            "sizing_rationale": "Final synthesis failed before reliable sizing guidance was available.",
            "risk_budget_note": "Generic risk guidance; not based on the user's actual holdings.",
        },
    }

    return f"""## Portfolio Manager Fallback Decision

{instrument_context}

**Rating**: HOLD

**Executive Summary**: {summary}

**Investment Thesis**: {thesis}

This fallback is intentionally conservative. It preserves the completed report artifacts while making clear that the final portfolio ruling was not authored by the Portfolio Manager model.

```json-highlights
{_json_block(highlights)}
```

```json-decision-card
{_json_block(decision_card)}
```"""


def _empty_portfolio_context(output_language: str | None) -> str:
    if (output_language or "en").lower() == "cn":
        return "当前持仓参考：\n- 未提供该用户的已跟踪持仓。"
    return "Current portfolio reference:\n- No tracked holdings were provided for this user."


def _format_opportunity_context(context: object, output_language: str) -> str:
    if not isinstance(context, dict) or not context:
        return ""
    trigger = context.get("trigger") or context.get("source") or "opportunity_radar"
    theme_name = context.get("theme_name") or context.get("theme_id") or "unknown"
    candidate_type = context.get("candidate_type") or "unknown"
    backtest = (
        context.get("backtest_summary")
        if isinstance(context.get("backtest_summary"), dict)
        else {}
    )
    sample_size = backtest.get("sample_size") if isinstance(backtest, dict) else None
    holding_periods = (
        backtest.get("holding_periods") if isinstance(backtest, dict) else None
    )
    if sample_size:
        historical = f"Historical signal sample size: {sample_size}; holding-period metrics: {holding_periods}."
    else:
        historical = "Historical validation is unavailable or sample size is insufficient. Do not invent win rate or returns."
    if output_language == "cn":
        return (
            "Opportunity Radar context:\n"
            f"- 机会来源: {trigger}\n"
            f"- 主题: {theme_name}\n"
            f"- 候选类型: {candidate_type}\n"
            f"- 历史验证: {historical}\n"
            "Use this only as upstream evidence. The DecisionCard remains your final ruling."
        )
    return (
        "Opportunity Radar context:\n"
        f"- Trigger: {trigger}\n"
        f"- Theme: {theme_name}\n"
        f"- Candidate type: {candidate_type}\n"
        f"- Validation: {historical}\n"
        "Use this only as upstream evidence. The DecisionCard remains your final ruling."
    )


class PortfolioManager(DivergeAgentNode):
    name = "portfolio_manager"

    def run(self, state) -> dict:
        instrument_context = build_instrument_context(state["company_of_interest"])

        history = state["risk_debate_state"]["history"]
        risk_debate_state = state["risk_debate_state"]
        market_research_report = state["market_report"]
        news_report = state["news_report"]
        fundamentals_report = state["fundamentals_report"]
        sentiment_report = state["sentiment_report"]
        trader_plan = state["investment_plan"]
        output_language = state.get("output_language", "en")
        language_instruction = get_language_instruction(output_language)
        style_instruction = get_research_note_style_instruction(output_language)
        trade_feedback_message = get_trade_feedback_message(state)
        evidence_rules_instruction = get_evidence_rules_instruction()
        portfolio_context = (state.get("portfolio_context") or "").strip()
        portfolio_context_block = (
            portfolio_context
            if portfolio_context
            else _empty_portfolio_context(output_language)
        )
        opportunity_context_block = _format_opportunity_context(
            state.get("opportunity_context"), output_language
        )

        curr_situation = (
            f"{market_research_report}\n\n{sentiment_report}\n\n"
            f"{news_report}\n\n{fundamentals_report}"
        )
        past_memories = self.memory.get_memories(curr_situation, n_matches=2)

        past_memory_str = ""
        if past_memories:
            for rec in past_memories:
                past_memory_str += rec["recommendation"] + "\n\n"
        else:
            past_memory_str = "No past memories found."

        prompt = f"""As the Portfolio Manager, synthesize the risk analysts' debate and deliver the final trading decision.

Final decision authority: you are the only agent allowed to issue the user-facing portfolio rating and action. Treat upstream `signal` values as legacy directional inputs, not final verdicts. Base the final DecisionCard on evidence quality, portfolio context, risk budget, and data limitations.

{evidence_rules_instruction}

{instrument_context}

{portfolio_context_block}

{opportunity_context_block}

Guidelines for Decision-Making:
1. **Summarize Key Arguments**: Extract the strongest points from each analyst, focusing on relevance to the context.
2. **Provide Rationale**: Support your recommendation with direct evidence and counterarguments from the debate.
3. **Refine the Trader's Plan**: Start with the trader's original plan, **{trader_plan}**, and adjust it based on the analysts' insights.
4. **Learn from Past Mistakes**: Use lessons from **{past_memory_str}** to address prior misjudgments and improve the decision you are making now.
5. **Use Portfolio Context Carefully**: If portfolio context is provided, you may use it to calibrate the final rating/action and narrative. For the structured DecisionCard intelligence fields, do not assume or disclose user-specific current exposure. Position guidance must be generic, risk-based, and suitable for a user who may have no recorded position.
6. **Use Opportunity Context Safely**: If Opportunity Radar context is provided, cite only its explicit trigger, theme, candidate type, and historical validation fields. If historical validation is unavailable or sample size is insufficient, state that clearly and do not invent win rates or returns.
7. **Keep Internal Context Private**: Use the portfolio context only to adjust exposure-aware advice. Do not quote raw ledger lines, account names, JSON/code-fence names, prompt labels, or internal implementation terms in user-facing prose. For Chinese output, describe this naturally as "持仓参考" or "现有持仓".

---

**Rating Scale** (use exactly one):
- **Buy**: Strong conviction to enter or add to position
- **Overweight**: Favorable outlook, gradually increase exposure
- **Hold**: Maintain current position, no action needed
- **Underweight**: Reduce exposure, take partial profits
- **Sell**: Exit position or avoid entry

**Context:**
- Trader's proposed plan: **{trader_plan}**
- Lessons from past decisions: **{past_memory_str}**
{trade_feedback_message}

**Required Output Structure:**
1. **Rating**: State one of Buy / Overweight / Hold / Underweight / Sell.
2. **Executive Summary**: A concise action plan covering entry strategy, position sizing, key risk levels, and time horizon.
3. **Investment Thesis**: Detailed reasoning anchored in the analysts' debate and past reflections.

---

**Risk Analysts Debate History:**
{history}

---

Be decisive and ground every conclusion in specific evidence from the analysts.

After your complete decision, append a structured highlights block:

```json-highlights
{{
  "category": "portfolio_decision",
  "signal": "BUY or OVERWEIGHT or HOLD or UNDERWEIGHT or SELL",
  "signal_confidence": "high or medium or low",
  "summary": "1-2 sentence executive summary of your final ruling",
  "final_decision": "BUY or OVERWEIGHT or HOLD or UNDERWEIGHT or SELL",
  "decision_basis": "one sentence explaining the primary reason",
  "strategic_actions": [
    {{
      "action": "action description",
      "priority": "immediate or conditional or long-term"
    }}
  ],
  "risk_warnings": ["warning 1", "warning 2"]
}}
```

After the json-highlights block, append a second structured block:

```json-decision-card
{{
  "card_version": "1.1",
  "rating": "BUY or OVERWEIGHT or HOLD or UNDERWEIGHT or SELL",
  "action": "OPEN or ADD or MAINTAIN or TRIM or EXIT or WATCH or NO_ACTION or AVOID",
  "confidence": "high or medium or low",
  "conviction_score": 0,
  "time_horizon": "short phrase, e.g. 5-20 trading days",
  "one_line_summary": "one sentence actionable summary",
  "thesis": "2-3 sentence investment thesis",
  "price_plan": {{
    "current_price": null,
    "entry_zone": null,
    "add_condition": "condition for adding or opening position",
    "stop_loss": null,
    "take_profit": null,
    "invalidation": ["condition that invalidates the thesis"],
    "risk_reward_note": "brief risk/reward comment"
  }},
  "suggested_position": "position sizing guidance, or null",
  "key_reasons": [
    {{
      "pillar": "technical or fundamentals or valuation or news or sentiment or risk or portfolio or macro",
      "point": "short reason",
      "evidence": "specific evidence from the analysts' reports",
      "strength": "strong or medium or weak",
      "source": "agent/report/tool source, or unknown",
      "data_date": "YYYY-MM-DD or unknown",
      "confidence": "high or medium or low",
      "limitation": "missing/stale/ambiguous input, or null"
    }}
  ],
  "key_risks": ["risk 1", "risk 2"],
  "catalysts": ["catalyst 1"],
  "watch_items": ["what to monitor next"],
  "data_quality_notes": ["data limitation, missing input, or stale source warning"],
  "trade_readiness": "READY or WAITING_FOR_TRIGGER or BLOCKED_BY_RISK or DATA_INSUFFICIENT or NO_ACTION_REQUIRED",
  "trade_readiness_reason": "one sentence explaining whether the setup is actionable now",
  "blocking_items": ["items preventing action now"],
  "data_quality_level": "complete or partial or weak or insufficient",
  "data_quality_summary": "one sentence explaining how data quality affects the decision",
  "why_not": {{
    "why_not_more_bullish": "why the ruling is not more bullish",
    "why_not_more_bearish": "why the ruling is not more bearish",
    "why_not_act_now": "why the user should not act more aggressively right now"
  }},
  "action_playbook": {{
    "do_now": ["immediate action or no-action instruction"],
    "trigger_to_act": ["condition that would justify action"],
    "invalidation": ["condition that invalidates the thesis or action plan"],
    "execution_notes": ["generic execution note, optional"]
  }},
  "position_guidance": {{
    "suggested_exposure": "generic risk-based sizing guidance, or null",
    "max_exposure": "generic maximum exposure guidance, or null",
    "sizing_rationale": "generic sizing rationale, or null",
    "risk_budget_note": "generic risk budget note, not user-specific"
  }}
}}
```

Keep the `json-highlights` and `json-decision-card` fences, JSON keys, and enum literals in English exactly as shown, even when the rest of the report is in another language. Free-form string values should follow the report language. Do not invent exact price levels if the reports do not provide reliable current price or technical levels. If price levels are unavailable, use null and explain the limitation in data_quality_notes. Rating and action are different concepts. Conviction_score reflects opportunity, risk, evidence strength, and data quality. Key_reasons must cite concrete evidence from analyst reports.
Do not generate Portfolio Fit, Decision Journal, Opportunity Queue, or Conviction Breakdown fields. Do not write phrases such as "your current position", "your portfolio", "你当前仓位", or "你的组合" inside `position_guidance`; keep it generic and risk-based.

{style_instruction}
{language_instruction}"""

        runtime_warnings = list(state.get("runtime_warnings") or [])
        try:
            response = self.llm.invoke(AdkPrompt(system_message=prompt))
            response_content = response.content
        except Exception as exc:
            if not _is_transient_llm_error(exc):
                raise
            logger.exception(
                "Portfolio Manager LLM failed with a transient error; using fallback final decision."
            )
            response_content = _build_fallback_portfolio_decision(
                instrument_context=instrument_context,
                error=exc,
            )
            runtime_warnings.append(_format_transient_llm_warning(exc))

        new_risk_debate_state = {
            "judge_decision": response_content,
            "history": risk_debate_state["history"],
            "aggressive_history": risk_debate_state["aggressive_history"],
            "conservative_history": risk_debate_state["conservative_history"],
            "neutral_history": risk_debate_state["neutral_history"],
            "latest_speaker": "Judge",
            "current_aggressive_response": risk_debate_state[
                "current_aggressive_response"
            ],
            "current_conservative_response": risk_debate_state[
                "current_conservative_response"
            ],
            "current_neutral_response": risk_debate_state["current_neutral_response"],
            "count": risk_debate_state["count"],
        }

        return {
            "risk_debate_state": new_risk_debate_state,
            "final_trade_decision": response_content,
            "runtime_warnings": runtime_warnings,
        }


def create_portfolio_manager(llm, memory):
    return PortfolioManager(llm, memory)
