import json
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from diverge.agents.utils.agent_utils import (
    build_instrument_context,
    format_untrusted_context_block,
    get_evidence_rules_instruction,
    get_language_instruction,
    get_memory_skepticism_instruction,
    get_research_note_style_instruction,
    get_trade_feedback_message,
)
from diverge.decision_card.schema import (
    ActionPlaybook,
    ConfidenceLevel,
    DataQualityLevel,
    EvidenceItem,
    PortfolioAction,
    PortfolioRating,
    PositionGuidance,
    PricePlan,
    TradeReadiness,
    WhyNot,
)
from diverge.decision_card.parser import (
    infer_action_from_rating,
    normalize_action,
    normalize_confidence,
    normalize_rating,
)


def _error_status_code(error: BaseException) -> int | None:
    status_code = getattr(error, "status_code", None)
    if isinstance(status_code, int):
        return status_code

    response = getattr(error, "response", None)
    response_status = getattr(response, "status_code", None)
    if isinstance(response_status, int):
        return response_status

    return None


def _is_transient_llm_error(error: BaseException) -> bool:
    status_code = _error_status_code(error)
    if status_code in {408, 409, 429, 500, 502, 503, 504}:
        return True

    message = str(error).lower()
    return (
        "gateway time-out" in message
        or "gateway timeout" in message
        or "connection error" in message
        or "connection reset" in message
        or "unexpected_eof_while_reading" in message
        or "eof occurred in violation of protocol" in message
        or "timed out" in message
        or "timeout" in message
        or "temporarily unavailable" in message
    )


def _json_block(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _format_transient_llm_warning(error: BaseException) -> dict[str, str]:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    return {
        "stage": "Portfolio Manager",
        "kind": "transient_llm_error",
        "message": (
            "Portfolio Manager used a conservative fallback because the LLM request "
            f"failed with a transient connection error: {error_note}"
        ),
    }


def _format_structured_output_warning(error: BaseException) -> dict[str, str]:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    return {
        "stage": "Portfolio Manager",
        "kind": "structured_output_validation_failed",
        "message": (
            "Portfolio Manager response did not match the ADK output schema; "
            "using raw model text and legacy decision-card fallback. "
            f"Error type: {error.__class__.__name__}; detail: {error_note}"
        ),
    }


def _build_fallback_portfolio_highlights() -> dict:
    summary = (
        "Portfolio Manager LLM request failed before producing a final ruling; "
        "treat this as a low-confidence no-action fallback and review the full report."
    )
    return {
        "category": "portfolio_decision",
        "signal": "HOLD",
        "signal_confidence": "low",
        "summary": summary,
        "final_decision": "HOLD",
        "decision_basis": "Final Portfolio Manager synthesis was unavailable due to an upstream transient LLM connection failure.",
        "strategic_actions": [
            {
                "action": "Review the full report manually before taking action.",
                "priority": "immediate",
            }
        ],
        "risk_warnings": [
            "Final portfolio ruling was generated by fallback logic.",
            "LLM gateway connection failure may have prevented risk adjustments from being synthesized.",
        ],
    }


def _build_fallback_portfolio_decision_card(error: BaseException) -> dict:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    summary = (
        "Portfolio Manager LLM request failed before producing a final ruling; "
        "treat this as a low-confidence no-action fallback and review the full report."
    )
    thesis = (
        "The analyst, trader, and risk debate sections were generated, but the final "
        "Portfolio Manager synthesis could not be completed because the model gateway "
        "returned a transient connection error."
    )
    return {
        "card_version": "1.2",
        "rating": "HOLD",
        "action": "NO_ACTION",
        "confidence": "low",
        "conviction_score": 0,
        "time_horizon": "Manual review required",
        "one_line_summary": summary,
        "thesis": thesis,
        "price_plan": {
            "current_price": None,
            "entry_zone": None,
            "add_condition": None,
            "stop_loss": None,
            "take_profit": None,
            "invalidation": [
                "A reliable Portfolio Manager final ruling is regenerated successfully."
            ],
            "risk_reward_note": "No risk/reward plan was generated because final synthesis timed out.",
        },
        "suggested_position": None,
        "key_reasons": [
            {
                "pillar": "portfolio",
                "point": "Fallback final ruling",
                "evidence": "The Portfolio Manager LLM call failed after retryable transient connection handling.",
                "strength": "weak",
            }
        ],
        "key_risks": [
            "No authoritative final Portfolio Manager synthesis is available.",
            "The user must inspect the analyst and risk debate sections manually.",
        ],
        "catalysts": [],
        "watch_items": [
            "Regenerate the Portfolio Manager decision when the LLM gateway connection is stable."
        ],
        "data_quality_notes": [
            "Fallback decision generated after transient LLM connection failure.",
            f"Upstream error: {error_note}",
        ],
        "trade_readiness": "DATA_INSUFFICIENT",
        "trade_readiness_reason": "Structured Portfolio Manager synthesis was unavailable, so no execution call is reliable.",
        "blocking_items": ["Regenerate the Portfolio Manager decision."],
        "data_quality_level": "insufficient",
        "data_quality_summary": "The final decision is a fallback because Portfolio Manager synthesis failed.",
        "why_not": {
            "why_not_more_bullish": "The final Portfolio Manager synthesis did not complete.",
            "why_not_more_bearish": "The completed analyst sections still need manual review before a stronger negative ruling.",
            "why_not_act_now": "The structured final ruling is unavailable and should be regenerated first.",
        },
        "action_playbook": {
            "do_now": ["Review the full report manually before taking action."],
            "trigger_to_act": [
                "Regenerate the Portfolio Manager decision successfully."
            ],
            "invalidation": [
                "A reliable Portfolio Manager final ruling is regenerated successfully."
            ],
            "execution_notes": ["No trading action should rely on this fallback card."],
        },
        "position_guidance": {
            "suggested_exposure": "No new risk exposure should be based on this fallback card.",
            "max_exposure": None,
            "sizing_rationale": "Final synthesis failed before reliable sizing guidance was available.",
            "risk_budget_note": "Generic risk guidance; not based on the user's actual holdings.",
        },
    }


def _build_fallback_portfolio_decision(
    *, instrument_context: str, error: BaseException
) -> str:
    highlights = _build_fallback_portfolio_highlights()
    decision_card = _build_fallback_portfolio_decision_card(error)
    summary = decision_card["one_line_summary"]
    thesis = decision_card["thesis"]

    return f"""## Portfolio Manager Fallback Decision

{instrument_context}

**Rating**: HOLD

**Executive Summary**: {summary}

**Investment Thesis**: {thesis}

This fallback is intentionally conservative. It preserves the completed report artifacts while making clear that the final portfolio ruling was not authored by the Portfolio Manager model.

```json-highlights
{_json_block(highlights)}
```

```json-decision-card
{_json_block(decision_card)}
```"""


def structured_fallback_from_transient_error(
    *,
    instrument_context: str,
    error: BaseException,
) -> "PortfolioManagerStructuredOutput":
    decision_card = _build_fallback_portfolio_decision_card(error)
    report = f"""## Portfolio Manager Fallback Decision

{instrument_context}

**Rating**: HOLD

**Executive Summary**: {decision_card["one_line_summary"]}

**Investment Thesis**: {decision_card["thesis"]}

This fallback is intentionally conservative. It preserves the completed report artifacts while making clear that the final portfolio ruling was not authored by the Portfolio Manager model."""
    return PortfolioManagerStructuredOutput.model_validate(
        {
            "decision_report": report,
            "decision_card": decision_card,
        }
    )


def _empty_portfolio_context(output_language: str | None) -> str:
    if (output_language or "en").lower() == "cn":
        return "当前持仓参考：\n- 未提供该用户的已跟踪持仓。"
    return "Current portfolio reference:\n- No tracked holdings were provided for this user."


def _clean_string(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    cleaned = value.strip()
    return cleaned or None


def _compact_summary(value: Any, *, max_chars: int = 180) -> str | None:
    cleaned = _clean_string(value)
    if not cleaned:
        return None
    compacted = " ".join(cleaned.split())
    for marker in ("。", ".", "！", "!", "？", "?"):
        marker_index = compacted.find(marker)
        if 0 < marker_index < max_chars:
            return compacted[: marker_index + 1]
    if len(compacted) > max_chars:
        return f"{compacted[:max_chars].rstrip()}..."
    return compacted


def _coerce_string_list(value: Any, *, max_items: int = 5) -> list[str]:
    if isinstance(value, str):
        cleaned = value.strip()
        return [cleaned] if cleaned else []
    if not isinstance(value, list):
        return []
    result = []
    for item in value:
        cleaned = _clean_string(item)
        if cleaned:
            result.append(cleaned)
        if len(result) >= max_items:
            break
    return result


def _coerce_evidence_items(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    items: list[dict[str, Any]] = []
    for raw in value:
        if isinstance(raw, str):
            evidence = raw.strip()
            if evidence:
                items.append(
                    {
                        "pillar": "portfolio",
                        "point": _compact_summary(evidence, max_chars=72)
                        or "Portfolio evidence",
                        "evidence": evidence,
                        "strength": "medium",
                    }
                )
        elif isinstance(raw, dict):
            point = _clean_string(raw.get("point") or raw.get("claim"))
            evidence = _clean_string(raw.get("evidence") or raw.get("claim"))
            if point:
                items.append(
                    {
                        "pillar": raw.get("pillar")
                        if isinstance(raw.get("pillar"), str)
                        else "portfolio",
                        "point": point,
                        "evidence": evidence or point,
                        "strength": raw.get("strength")
                        if isinstance(raw.get("strength"), str)
                        else "medium",
                        "source": raw.get("source")
                        if isinstance(raw.get("source"), str)
                        else None,
                        "data_date": raw.get("data_date")
                        if isinstance(raw.get("data_date"), str)
                        else None,
                        "confidence": normalize_confidence(raw.get("confidence"))
                        if isinstance(raw.get("confidence"), str)
                        else None,
                        "limitation": raw.get("limitation")
                        if isinstance(raw.get("limitation"), str)
                        else None,
                    }
                )
        if len(items) >= 5:
            break
    return items


def _normalize_partial_decision_card_payload(card: dict[str, Any]) -> dict[str, Any]:
    rating = normalize_rating(str(card.get("rating")) if card.get("rating") else None)
    thesis = (
        _clean_string(card.get("thesis"))
        or _clean_string(card.get("decision_basis"))
        or _clean_string(card.get("decision_report"))
        or "Portfolio Manager provided a partial structured decision card."
    )
    summary = (
        _clean_string(card.get("one_line_summary"))
        or _clean_string(card.get("summary"))
        or _compact_summary(thesis)
        or "Portfolio Manager provided a partial structured decision card."
    )
    key_reasons = _coerce_evidence_items(
        card.get("key_reasons") or card.get("evidence_blocks")
    )
    key_risks = _coerce_string_list(card.get("key_risks"))
    risk_summary = _clean_string(card.get("risk_summary"))
    if not key_risks and risk_summary:
        key_risks = [risk_summary]
    position_guidance = card.get("position_guidance")
    if isinstance(position_guidance, str):
        position_guidance = {
            "suggested_exposure": position_guidance,
            "max_exposure": None,
            "sizing_rationale": None,
            "risk_budget_note": None,
        }
    data_quality_notes = _coerce_string_list(
        card.get("data_quality_notes"), max_items=20
    )
    data_quality_notes.append(
        "Recovered from a schema-invalid Portfolio Manager response."
    )

    return {
        "card_version": card.get("card_version") or "1.2",
        "rating": rating,
        "action": normalize_action(
            str(card.get("action")) if card.get("action") else None, rating
        )
        or infer_action_from_rating(rating),
        "confidence": normalize_confidence(
            str(card.get("confidence")) if card.get("confidence") else None
        ),
        "conviction_score": card.get("conviction_score")
        if isinstance(card.get("conviction_score"), int)
        else 50,
        "time_horizon": _clean_string(card.get("time_horizon")) or "Not specified",
        "one_line_summary": summary,
        "thesis": thesis,
        "price_plan": card.get("price_plan")
        if isinstance(card.get("price_plan"), dict)
        else {},
        "suggested_position": _clean_string(card.get("suggested_position")),
        "key_reasons": key_reasons,
        "key_risks": key_risks,
        "catalysts": _coerce_string_list(card.get("catalysts")),
        "watch_items": _coerce_string_list(card.get("watch_items")),
        "data_quality_notes": data_quality_notes,
        "trade_readiness": card.get("trade_readiness"),
        "trade_readiness_reason": _clean_string(card.get("trade_readiness_reason")),
        "blocking_items": _coerce_string_list(card.get("blocking_items")),
        "data_quality_level": card.get("data_quality_level"),
        "data_quality_summary": _clean_string(card.get("data_quality_summary")),
        "why_not": card.get("why_not") if isinstance(card.get("why_not"), dict) else None,
        "action_playbook": card.get("action_playbook")
        if isinstance(card.get("action_playbook"), dict)
        else None,
        "position_guidance": position_guidance
        if isinstance(position_guidance, dict)
        else None,
    }


def _salvage_structured_output(
    raw_response: str,
) -> "PortfolioManagerStructuredOutput | None":
    try:
        payload = json.loads(raw_response or "")
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, dict):
        return None
    decision_card = payload.get("decision_card")
    if not isinstance(decision_card, dict):
        return None
    has_substance = any(
        decision_card.get(key)
        for key in (
            "one_line_summary",
            "summary",
            "thesis",
            "key_reasons",
            "evidence_blocks",
        )
    )
    if not has_substance:
        return None
    decision_report = _clean_string(payload.get("decision_report")) or (
        "## Portfolio Manager Decision\n\n"
        + (
            _clean_string(decision_card.get("thesis"))
            or "Portfolio Manager provided a partial structured decision card."
        )
    )
    return PortfolioManagerStructuredOutput.model_validate(
        {
            "decision_report": decision_report,
            "decision_card": _normalize_partial_decision_card_payload(decision_card),
        }
    )


class PortfolioDecisionCardOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    card_version: str = Field(
        default="1.2",
        description="DecisionCard schema version. Use '1.2' unless instructed otherwise.",
    )
    rating: PortfolioRating = Field(
        description=(
            "Final portfolio rating. Use exactly one enum: BUY, OVERWEIGHT, HOLD, "
            "UNDERWEIGHT, or SELL."
        )
    )
    action: PortfolioAction = Field(
        description=(
            "Execution action, distinct from rating. Use OPEN, ADD, MAINTAIN, TRIM, "
            "EXIT, WATCH, NO_ACTION, or AVOID."
        )
    )
    confidence: ConfidenceLevel = Field(
        description="Overall confidence in the final ruling: high, medium, or low."
    )
    conviction_score: int = Field(
        ge=0,
        le=100,
        description=(
            "0-100 conviction score reflecting opportunity, risk, evidence strength, "
            "and data quality."
        ),
    )
    time_horizon: str = Field(
        description=(
            "Required short horizon such as 'Not specified', '1-4 weeks', or "
            "'next earnings cycle'. Do not omit."
        )
    )
    one_line_summary: str = Field(
        description="Required one-sentence user-facing summary of the final decision."
    )
    thesis: str = Field(
        description="Required concise thesis explaining the final decision and main caveats."
    )
    price_plan: PricePlan = Field(
        default_factory=PricePlan,
        description=(
            "Execution price plan. Use null for price levels when reliable current "
            "price or technical levels are unavailable."
        ),
    )
    suggested_position: str | None = Field(
        default=None,
        description=(
            "Optional generic suggested position text. Do not assume real user holdings."
        ),
    )
    key_reasons: list[EvidenceItem] = Field(
        default_factory=list,
        max_length=5,
        description=(
            "Array of evidence objects, not strings. Each item must include pillar, "
            "point, evidence, and strength."
        ),
    )
    key_risks: list[str] = Field(
        default_factory=list,
        max_length=5,
        description=(
            "Risk summary bullets. Use this field instead of creating risk_summary."
        ),
    )
    catalysts: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="Optional catalyst bullets explicitly supported by the reports.",
    )
    watch_items: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="Optional monitoring items or triggers to revisit the decision.",
    )
    data_quality_notes: list[str] = Field(
        default_factory=list,
        max_length=20,
        description="Data limitations, missing inputs, and confidence caveats.",
    )
    trade_readiness: TradeReadiness | None = Field(
        default=None,
        description=(
            "Execution readiness: READY, WAITING_FOR_TRIGGER, BLOCKED_BY_RISK, "
            "DATA_INSUFFICIENT, NO_ACTION_REQUIRED, or null."
        ),
    )
    trade_readiness_reason: str | None = Field(
        default=None,
        description="Optional brief reason for trade_readiness.",
    )
    blocking_items: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="Specific missing inputs or risk blockers before action.",
    )
    data_quality_level: DataQualityLevel | None = Field(
        default=None,
        description="complete, partial, weak, insufficient, or null.",
    )
    data_quality_summary: str | None = Field(
        default=None,
        description="Optional user-facing summary of data quality.",
    )
    why_not: WhyNot | None = Field(
        default=None,
        description="Optional structured alternatives explaining why not more bullish, bearish, or immediate.",
    )
    action_playbook: ActionPlaybook | None = Field(
        default=None,
        description="Optional structured execution playbook.",
    )
    position_guidance: PositionGuidance | None = Field(
        default=None,
        description=(
            "Optional object with generic exposure guidance. Do not provide this as a string."
        ),
    )


class PortfolioManagerStructuredOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    decision_report: str = Field(
        description=(
            "User-facing Portfolio Manager markdown narrative without JSON code "
            "fences. Include these sections inside this field: ## Rating, "
            "## Executive Summary, and ## Investment Thesis. Do not wrap the "
            "field in an outer heading named `decision_report`, and do not "
            "include a heading named `decision_card`."
        )
    )
    decision_card: PortfolioDecisionCardOutput = Field(
        description=(
            "Structured final decision card matching PortfolioDecisionCardOutput exactly. "
            "Do not add unsupported fields such as ticker or risk_summary."
        )
    )


def _fallback_decision_card_for_structured_error(error: BaseException) -> dict:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    return {
        "card_version": "1.2",
        "rating": "HOLD",
        "action": "NO_ACTION",
        "confidence": "low",
        "conviction_score": 0,
        "time_horizon": "Manual review required",
        "one_line_summary": "Portfolio Manager returned a response that could not be validated against the structured DecisionCard schema.",
        "thesis": "The model produced a final Portfolio Manager response, but its structured payload did not match the required schema, so this conservative card preserves the report while blocking automated action.",
        "price_plan": {
            "current_price": None,
            "entry_zone": None,
            "add_condition": None,
            "stop_loss": None,
            "take_profit": None,
            "invalidation": [
                "Regenerate a schema-valid Portfolio Manager decision."
            ],
            "risk_reward_note": "No reliable price plan was available from the invalid structured response.",
        },
        "suggested_position": None,
        "key_reasons": [
            {
                "pillar": "portfolio",
                "point": "Structured validation failed",
                "evidence": "The Portfolio Manager response could not be parsed into PortfolioManagerStructuredOutput.",
                "strength": "weak",
            }
        ],
        "key_risks": [
            "Automated action is blocked until a schema-valid final decision is generated."
        ],
        "catalysts": [],
        "watch_items": [
            "Regenerate the Portfolio Manager decision with strict schema validation."
        ],
        "data_quality_notes": [
            "Fallback decision generated after structured output validation failure.",
            f"Validation error: {error_note}",
        ],
        "trade_readiness": "DATA_INSUFFICIENT",
        "trade_readiness_reason": "The final Portfolio Manager structured payload was invalid.",
        "blocking_items": ["Regenerate a schema-valid Portfolio Manager decision."],
        "data_quality_level": "insufficient",
        "data_quality_summary": "Final decision card is conservative because schema validation failed.",
        "why_not": {
            "why_not_more_bullish": "The final structured evidence payload was invalid.",
            "why_not_more_bearish": "The unstructured report may still contain useful context and requires manual review.",
            "why_not_act_now": "The structured DecisionCard is not reliable enough for automated action.",
        },
        "action_playbook": {
            "do_now": ["Review the raw Portfolio Manager response manually."],
            "trigger_to_act": [
                "A regenerated Portfolio Manager response validates against the schema."
            ],
            "invalidation": [
                "The original invalid response is replaced by a valid structured decision."
            ],
            "execution_notes": [
                "No trade should rely only on this schema-validation fallback card."
            ],
        },
        "position_guidance": {
            "suggested_exposure": "No new risk exposure should be based on this fallback card.",
            "max_exposure": None,
            "sizing_rationale": "Structured sizing guidance was unavailable.",
            "risk_budget_note": "Generic risk guidance; not based on current holdings.",
        },
    }


def structured_fallback_from_invalid_response(
    raw_response: str,
    error: BaseException,
) -> PortfolioManagerStructuredOutput:
    salvaged = _salvage_structured_output(raw_response)
    if salvaged is not None:
        return salvaged

    report = raw_response.strip()
    if not report:
        report = (
            "## Portfolio Manager Decision\n\n"
            "The model response was empty or invalid, so Diverge generated a "
            "conservative schema-validation fallback."
        )
    return PortfolioManagerStructuredOutput.model_validate(
        {
            "decision_report": report,
            "decision_card": _fallback_decision_card_for_structured_error(error),
        }
    )


def portfolio_structured_output_warning(error: BaseException) -> dict[str, str]:
    return _format_structured_output_warning(error)


def portfolio_transient_llm_warning(error: BaseException) -> dict[str, str]:
    return _format_transient_llm_warning(error)


def is_transient_portfolio_llm_error(error: BaseException) -> bool:
    return _is_transient_llm_error(error)


def _highlights_from_decision_card(card: PortfolioDecisionCardOutput) -> dict:
    actions = []
    if card.action_playbook and card.action_playbook.do_now:
        actions = [
            {"action": action, "priority": "immediate"}
            for action in card.action_playbook.do_now[:3]
        ]
    elif card.price_plan.add_condition:
        actions = [{"action": card.price_plan.add_condition, "priority": "conditional"}]

    return {
        "category": "portfolio_decision",
        "signal": card.rating,
        "signal_confidence": card.confidence,
        "summary": card.one_line_summary,
        "final_decision": card.rating,
        "decision_basis": card.thesis,
        "strategic_actions": actions,
        "risk_warnings": card.key_risks,
    }


def _render_structured_portfolio_decision(
    structured: PortfolioManagerStructuredOutput,
) -> str:
    report = structured.decision_report.strip()
    if not report:
        report = (
            f"## Portfolio Manager Decision\n\n"
            f"**Rating**: {structured.decision_card.rating}\n\n"
            f"**Executive Summary**: {structured.decision_card.one_line_summary}\n\n"
            f"**Investment Thesis**: {structured.decision_card.thesis}"
        )
    highlights = _highlights_from_decision_card(structured.decision_card)
    decision_card = structured.decision_card.model_dump(mode="json")
    return f"""{report}

```json-highlights
{_json_block(highlights)}
```

```json-decision-card
{_json_block(decision_card)}
```"""


def _format_opportunity_context(context: object, output_language: str) -> str:
    if not isinstance(context, dict) or not context:
        return ""
    trigger = context.get("trigger") or context.get("source") or "opportunity_radar"
    theme_name = context.get("theme_name") or context.get("theme_id") or "unknown"
    candidate_type = context.get("candidate_type") or "unknown"
    backtest = (
        context.get("backtest_summary")
        if isinstance(context.get("backtest_summary"), dict)
        else {}
    )
    sample_size = backtest.get("sample_size") if isinstance(backtest, dict) else None
    holding_periods = (
        backtest.get("holding_periods") if isinstance(backtest, dict) else None
    )
    if sample_size:
        historical = f"Historical signal sample size: {sample_size}; holding-period metrics: {holding_periods}."
    else:
        historical = "Historical validation is unavailable or sample size is insufficient. Do not invent win rate or returns."
    if output_language == "cn":
        return (
            "Opportunity Radar context:\n"
            f"- 机会来源: {trigger}\n"
            f"- 主题: {theme_name}\n"
            f"- 候选类型: {candidate_type}\n"
            f"- 历史验证: {historical}\n"
            "Use this only as upstream evidence. The DecisionCard remains your final ruling."
        )
    return (
        "Opportunity Radar context:\n"
        f"- Trigger: {trigger}\n"
        f"- Theme: {theme_name}\n"
        f"- Candidate type: {candidate_type}\n"
        f"- Validation: {historical}\n"
        "Use this only as upstream evidence. The DecisionCard remains your final ruling."
    )


def build_portfolio_manager_prompt(
    state: dict,
    memory,
) -> tuple[str, dict[str, object]]:
    instrument_context = build_instrument_context(state["company_of_interest"])

    history = state["risk_debate_state"]["history"]
    risk_debate_state = state["risk_debate_state"]
    market_research_report = state["market_report"]
    news_report = state["news_report"]
    fundamentals_report = state["fundamentals_report"]
    sentiment_report = state["sentiment_report"]
    trader_plan = state["investment_plan"]
    output_language = state.get("output_language", "en")
    language_instruction = get_language_instruction(output_language)
    style_instruction = get_research_note_style_instruction(output_language)
    trade_feedback_message = get_trade_feedback_message(state)
    evidence_rules_instruction = get_evidence_rules_instruction()
    memory_skepticism_instruction = get_memory_skepticism_instruction()
    portfolio_context = (state.get("portfolio_context") or "").strip()
    portfolio_context_block = (
        portfolio_context
        if portfolio_context
        else _empty_portfolio_context(output_language)
    )
    opportunity_context_block = _format_opportunity_context(
        state.get("opportunity_context"), output_language
    )

    curr_situation = (
        f"{market_research_report}\n\n{sentiment_report}\n\n"
        f"{news_report}\n\n{fundamentals_report}"
    )
    past_memories = memory.get_memories(curr_situation, n_matches=2)

    past_memory_str = ""
    if past_memories:
        for rec in past_memories:
            past_memory_str += rec["recommendation"] + "\n\n"
    else:
        past_memory_str = "No past memories found."

    trader_plan_block = format_untrusted_context_block(
        "trader_plan",
        trader_plan,
        limit=6000,
    )
    past_memory_block = format_untrusted_context_block(
        "past_decision_memory",
        past_memory_str,
        limit=6000,
    )
    risk_history_block = format_untrusted_context_block(
        "risk_analysts_debate_history",
        history,
        limit=6000,
    )
    decision_card_schema_example = _json_block(
        {
            "decision_report": "## Rating\n\n...\n\n## Executive Summary\n\n...\n\n## Investment Thesis\n\n...",
            "decision_card": {
                "rating": "HOLD",
                "action": "WATCH",
                "confidence": "low",
                "conviction_score": 42,
                "time_horizon": "Not specified",
                "one_line_summary": "One concise user-facing sentence.",
                "thesis": "Concise thesis with the main evidence and caveats.",
                "key_reasons": [
                    {
                        "pillar": "portfolio",
                        "point": "Short decision point",
                        "evidence": "Concrete evidence from analyst reports or risk debate.",
                        "strength": "medium",
                        "source": "risk_debate",
                        "data_date": None,
                        "confidence": "medium",
                        "limitation": "Known data limitation, or null.",
                    }
                ],
                "key_risks": ["Risk summary bullet."],
                "data_quality_notes": ["Missing or weak input note."],
                "position_guidance": {
                    "suggested_exposure": "Generic risk-based exposure guidance.",
                    "max_exposure": None,
                    "sizing_rationale": None,
                    "risk_budget_note": "Generic risk guidance; do not assume real holdings.",
                },
            },
        }
    )

    prompt = f"""As the Portfolio Manager, synthesize the risk analysts' debate and deliver the final trading decision.

Final decision authority: you are the only agent allowed to issue the user-facing portfolio rating and action. Treat upstream `signal` values as legacy directional inputs, not final verdicts. Base the final DecisionCard on evidence quality, portfolio context, risk budget, and data limitations.

{evidence_rules_instruction}
{memory_skepticism_instruction}

{instrument_context}

{portfolio_context_block}

{opportunity_context_block}

Guidelines for Decision-Making:
1. **Summarize Key Arguments**: Extract the strongest points from each analyst, focusing on relevance to the context.
2. **Provide Rationale**: Support your recommendation with direct evidence and counterarguments from the debate.
3. **Refine the Trader's Plan**: Start with the trader plan in the untrusted context block below, and adjust it based on the analysts' insights.
4. **Learn from Past Mistakes**: Use lessons from the past-decision memory context block to address prior misjudgments and improve the decision you are making now.
5. **Use Portfolio Context Carefully**: If portfolio context is provided, you may use it to calibrate the final rating/action and narrative. For the structured DecisionCard intelligence fields, do not assume or disclose user-specific current exposure. Position guidance must be generic, risk-based, and suitable for a user who may have no recorded position.
6. **Use Opportunity Context Safely**: If Opportunity Radar context is provided, cite only its explicit trigger, theme, candidate type, and historical validation fields. If historical validation is unavailable or sample size is insufficient, state that clearly and do not invent win rates or returns.
7. **Keep Internal Context Private**: Use the portfolio context only to adjust exposure-aware advice. Do not quote raw ledger lines, account names, JSON/code-fence names, prompt labels, or internal implementation terms in user-facing prose. For Chinese output, describe this naturally as "持仓参考" or "现有持仓".

---

**Rating Scale** (use exactly one uppercase enum in `decision_card.rating`):
- **BUY**: Strong conviction to enter or add to position
- **OVERWEIGHT**: Favorable outlook, gradually increase exposure
- **HOLD**: Maintain current position, no action needed
- **UNDERWEIGHT**: Reduce exposure, take partial profits
- **SELL**: Exit position or avoid entry

**Context:**
{trader_plan_block}

{past_memory_block}

{trade_feedback_message}

**Risk Analysts Debate History:**
{risk_history_block}

---

Be decisive and ground every conclusion in specific evidence from the analysts.

Return only the structured response requested by the runtime schema:
- `decision_report`: user-facing markdown narrative without JSON code fences. Follow the section structure specified in the `decision_report` field description.
- `decision_card`: the structured final decision object.

	Top-level response must be exactly the schema object. Do not create markdown headings named `decision_report` or `decision_card`, and do not label the two schema fields as markdown sections.

	For `decision_card`, use English enum literals exactly:
- rating: BUY, OVERWEIGHT, HOLD, UNDERWEIGHT, SELL
- action: OPEN, ADD, MAINTAIN, TRIM, EXIT, WATCH, NO_ACTION, AVOID
- confidence: high, medium, low
	- trade_readiness: READY, WAITING_FOR_TRIGGER, BLOCKED_BY_RISK, DATA_INSUFFICIENT, NO_ACTION_REQUIRED
	- data_quality_level: complete, partial, weak, insufficient

	Minimum valid schema shape to follow. Do not return this as a fenced code block; return the raw schema object requested by the runtime:
	{decision_card_schema_example}

	Schema-shape rules:
	- `time_horizon`, `one_line_summary`, and `thesis` are required. If the horizon is unavailable, set `time_horizon` to "Not specified".
	- `key_reasons` must be an array of evidence objects. Never emit `key_reasons` as an array of strings.
	- Use `key_risks` for risk bullets. Do not create a separate `risk_summary` field.
	- `position_guidance` must be an object with `suggested_exposure`, `max_exposure`, `sizing_rationale`, and `risk_budget_note`, or null. Never emit it as a string.
	- Do not add unsupported fields such as `ticker`, `symbol`, `market`, or `risk_summary` inside `decision_card`.

	Do not invent exact price levels if the reports do not provide reliable current price or technical levels. If price levels are unavailable, use null and explain the limitation in data_quality_notes. Rating and action are different concepts. Conviction_score reflects opportunity, risk, evidence strength, and data quality. Key_reasons must cite concrete evidence from analyst reports.
	Do not generate Portfolio Fit, Decision Journal, Opportunity Queue, or Conviction Breakdown fields. Do not write phrases such as "your current position", "your portfolio", "你当前仓位", or "你的组合" inside `position_guidance`; keep it generic and risk-based.

{style_instruction}
{language_instruction}"""

    return prompt, {
        "instrument_context": instrument_context,
        "risk_debate_state": risk_debate_state,
        "runtime_warnings": list(state.get("runtime_warnings") or []),
    }


def build_portfolio_manager_result(
    *,
    state: dict,
    response_content: str,
    runtime_warnings: list[dict],
    portfolio_decision_card: dict | None = None,
    portfolio_decision_structured: dict | None = None,
) -> dict:
    risk_debate_state = state["risk_debate_state"]
    new_risk_debate_state = {
        "judge_decision": response_content,
        "history": risk_debate_state["history"],
        "aggressive_history": risk_debate_state["aggressive_history"],
        "conservative_history": risk_debate_state["conservative_history"],
        "neutral_history": risk_debate_state["neutral_history"],
        "latest_speaker": "Judge",
        "current_aggressive_response": risk_debate_state[
            "current_aggressive_response"
        ],
        "current_conservative_response": risk_debate_state[
            "current_conservative_response"
        ],
        "current_neutral_response": risk_debate_state["current_neutral_response"],
        "count": risk_debate_state["count"],
    }

    result = {
        "risk_debate_state": new_risk_debate_state,
        "final_trade_decision": response_content,
        "runtime_warnings": runtime_warnings,
    }
    if portfolio_decision_card is not None:
        result["portfolio_decision_card"] = portfolio_decision_card
    if portfolio_decision_structured is not None:
        result["portfolio_decision_structured"] = portfolio_decision_structured
    return result


def build_portfolio_manager_result_from_structured(
    *,
    state: dict,
    structured_payload: dict | PortfolioManagerStructuredOutput,
) -> dict:
    structured = (
        structured_payload
        if isinstance(structured_payload, PortfolioManagerStructuredOutput)
        else PortfolioManagerStructuredOutput.model_validate(structured_payload)
    )
    decision_card = structured.decision_card.model_dump(mode="json")
    structured_output = structured.model_dump(mode="json")
    return build_portfolio_manager_result(
        state=state,
        response_content=_render_structured_portfolio_decision(structured),
        runtime_warnings=list(state.get("runtime_warnings") or []),
        portfolio_decision_card=decision_card,
        portfolio_decision_structured=structured_output,
    )
