import json
import logging

from pydantic import BaseModel, Field

from diverge.agents.base import AgentCallSpec, DivergeAgentNode
from diverge.agents.utils.agent_utils import (
    build_instrument_context,
    get_evidence_rules_instruction,
    get_language_instruction,
    get_research_note_style_instruction,
    get_trade_feedback_message,
)
from diverge.decision_card.schema import (
    ActionPlaybook,
    ConfidenceLevel,
    DataQualityLevel,
    EvidenceItem,
    PortfolioAction,
    PortfolioRating,
    PositionGuidance,
    PricePlan,
    TradeReadiness,
    WhyNot,
)
from diverge.runtime.messages import AdkPrompt
from diverge.runtime.structured_output import parse_structured_output

logger = logging.getLogger(__name__)


def _error_status_code(error: BaseException) -> int | None:
    status_code = getattr(error, "status_code", None)
    if isinstance(status_code, int):
        return status_code

    response = getattr(error, "response", None)
    response_status = getattr(response, "status_code", None)
    if isinstance(response_status, int):
        return response_status

    return None


def _is_transient_llm_error(error: BaseException) -> bool:
    status_code = _error_status_code(error)
    if status_code in {408, 409, 429, 500, 502, 503, 504}:
        return True

    message = str(error).lower()
    return (
        "gateway time-out" in message
        or "gateway timeout" in message
        or "connection error" in message
        or "connection reset" in message
        or "unexpected_eof_while_reading" in message
        or "eof occurred in violation of protocol" in message
        or "timed out" in message
        or "timeout" in message
        or "temporarily unavailable" in message
    )


def _json_block(payload: dict) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _format_transient_llm_warning(error: BaseException) -> dict[str, str]:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    return {
        "stage": "Portfolio Manager",
        "kind": "transient_llm_error",
        "message": (
            "Portfolio Manager used a conservative fallback because the LLM request "
            f"failed with a transient connection error: {error_note}"
        ),
    }


def _format_structured_output_warning(error: BaseException) -> dict[str, str]:
    return {
        "stage": "Portfolio Manager",
        "kind": "structured_output_validation_failed",
        "message": (
            "Portfolio Manager response did not match the ADK output schema; "
            f"using raw model text and legacy decision-card fallback. Error type: {error.__class__.__name__}"
        ),
    }


def _build_fallback_portfolio_highlights() -> dict:
    summary = (
        "Portfolio Manager LLM request failed before producing a final ruling; "
        "treat this as a low-confidence no-action fallback and review the full report."
    )
    return {
        "category": "portfolio_decision",
        "signal": "HOLD",
        "signal_confidence": "low",
        "summary": summary,
        "final_decision": "HOLD",
        "decision_basis": "Final Portfolio Manager synthesis was unavailable due to an upstream transient LLM connection failure.",
        "strategic_actions": [
            {
                "action": "Review the full report manually before taking action.",
                "priority": "immediate",
            }
        ],
        "risk_warnings": [
            "Final portfolio ruling was generated by fallback logic.",
            "LLM gateway connection failure may have prevented risk adjustments from being synthesized.",
        ],
    }


def _build_fallback_portfolio_decision_card(error: BaseException) -> dict:
    error_note = str(error).strip()[:500] or error.__class__.__name__
    summary = (
        "Portfolio Manager LLM request failed before producing a final ruling; "
        "treat this as a low-confidence no-action fallback and review the full report."
    )
    thesis = (
        "The analyst, trader, and risk debate sections were generated, but the final "
        "Portfolio Manager synthesis could not be completed because the model gateway "
        "returned a transient connection error."
    )
    return {
        "card_version": "1.2",
        "rating": "HOLD",
        "action": "NO_ACTION",
        "confidence": "low",
        "conviction_score": 0,
        "time_horizon": "Manual review required",
        "one_line_summary": summary,
        "thesis": thesis,
        "price_plan": {
            "current_price": None,
            "entry_zone": None,
            "add_condition": None,
            "stop_loss": None,
            "take_profit": None,
            "invalidation": [
                "A reliable Portfolio Manager final ruling is regenerated successfully."
            ],
            "risk_reward_note": "No risk/reward plan was generated because final synthesis timed out.",
        },
        "suggested_position": None,
        "key_reasons": [
            {
                "pillar": "portfolio",
                "point": "Fallback final ruling",
                "evidence": "The Portfolio Manager LLM call failed after retryable transient connection handling.",
                "strength": "weak",
            }
        ],
        "key_risks": [
            "No authoritative final Portfolio Manager synthesis is available.",
            "The user must inspect the analyst and risk debate sections manually.",
        ],
        "catalysts": [],
        "watch_items": [
            "Regenerate the Portfolio Manager decision when the LLM gateway connection is stable."
        ],
        "data_quality_notes": [
            "Fallback decision generated after transient LLM connection failure.",
            f"Upstream error: {error_note}",
        ],
        "trade_readiness": "DATA_INSUFFICIENT",
        "trade_readiness_reason": "Structured Portfolio Manager synthesis was unavailable, so no execution call is reliable.",
        "blocking_items": ["Regenerate the Portfolio Manager decision."],
        "data_quality_level": "insufficient",
        "data_quality_summary": "The final decision is a fallback because Portfolio Manager synthesis failed.",
        "why_not": {
            "why_not_more_bullish": "The final Portfolio Manager synthesis did not complete.",
            "why_not_more_bearish": "The completed analyst sections still need manual review before a stronger negative ruling.",
            "why_not_act_now": "The structured final ruling is unavailable and should be regenerated first.",
        },
        "action_playbook": {
            "do_now": ["Review the full report manually before taking action."],
            "trigger_to_act": [
                "Regenerate the Portfolio Manager decision successfully."
            ],
            "invalidation": [
                "A reliable Portfolio Manager final ruling is regenerated successfully."
            ],
            "execution_notes": ["No trading action should rely on this fallback card."],
        },
        "position_guidance": {
            "suggested_exposure": "No new risk exposure should be based on this fallback card.",
            "max_exposure": None,
            "sizing_rationale": "Final synthesis failed before reliable sizing guidance was available.",
            "risk_budget_note": "Generic risk guidance; not based on the user's actual holdings.",
        },
    }


def _build_fallback_portfolio_decision(
    *, instrument_context: str, error: BaseException
) -> str:
    highlights = _build_fallback_portfolio_highlights()
    decision_card = _build_fallback_portfolio_decision_card(error)
    summary = decision_card["one_line_summary"]
    thesis = decision_card["thesis"]

    return f"""## Portfolio Manager Fallback Decision

{instrument_context}

**Rating**: HOLD

**Executive Summary**: {summary}

**Investment Thesis**: {thesis}

This fallback is intentionally conservative. It preserves the completed report artifacts while making clear that the final portfolio ruling was not authored by the Portfolio Manager model.

```json-highlights
{_json_block(highlights)}
```

```json-decision-card
{_json_block(decision_card)}
```"""


def _empty_portfolio_context(output_language: str | None) -> str:
    if (output_language or "en").lower() == "cn":
        return "当前持仓参考：\n- 未提供该用户的已跟踪持仓。"
    return "Current portfolio reference:\n- No tracked holdings were provided for this user."


class PortfolioDecisionCardOutput(BaseModel):
    card_version: str = "1.2"
    rating: PortfolioRating
    action: PortfolioAction
    confidence: ConfidenceLevel
    conviction_score: int = Field(ge=0, le=100)
    time_horizon: str
    one_line_summary: str
    thesis: str
    price_plan: PricePlan = Field(default_factory=PricePlan)
    suggested_position: str | None = None
    key_reasons: list[EvidenceItem] = Field(default_factory=list, max_length=5)
    key_risks: list[str] = Field(default_factory=list, max_length=5)
    catalysts: list[str] = Field(default_factory=list, max_length=5)
    watch_items: list[str] = Field(default_factory=list, max_length=5)
    data_quality_notes: list[str] = Field(default_factory=list, max_length=20)
    trade_readiness: TradeReadiness | None = None
    trade_readiness_reason: str | None = None
    blocking_items: list[str] = Field(default_factory=list, max_length=5)
    data_quality_level: DataQualityLevel | None = None
    data_quality_summary: str | None = None
    why_not: WhyNot | None = None
    action_playbook: ActionPlaybook | None = None
    position_guidance: PositionGuidance | None = None


class PortfolioManagerStructuredOutput(BaseModel):
    decision_report: str = Field(
        description=(
            "User-facing Portfolio Manager markdown narrative without JSON code "
            "fences. It should include the final rating, rationale, and action plan."
        )
    )
    decision_card: PortfolioDecisionCardOutput


def _highlights_from_decision_card(card: PortfolioDecisionCardOutput) -> dict:
    actions = []
    if card.action_playbook and card.action_playbook.do_now:
        actions = [
            {"action": action, "priority": "immediate"}
            for action in card.action_playbook.do_now[:3]
        ]
    elif card.price_plan.add_condition:
        actions = [{"action": card.price_plan.add_condition, "priority": "conditional"}]

    return {
        "category": "portfolio_decision",
        "signal": card.rating,
        "signal_confidence": card.confidence,
        "summary": card.one_line_summary,
        "final_decision": card.rating,
        "decision_basis": card.thesis,
        "strategic_actions": actions,
        "risk_warnings": card.key_risks,
    }


def _render_structured_portfolio_decision(
    structured: PortfolioManagerStructuredOutput,
) -> str:
    report = structured.decision_report.strip()
    if not report:
        report = (
            f"## Portfolio Manager Decision\n\n"
            f"**Rating**: {structured.decision_card.rating}\n\n"
            f"**Executive Summary**: {structured.decision_card.one_line_summary}\n\n"
            f"**Investment Thesis**: {structured.decision_card.thesis}"
        )
    highlights = _highlights_from_decision_card(structured.decision_card)
    decision_card = structured.decision_card.model_dump(mode="json")
    return f"""{report}

```json-highlights
{_json_block(highlights)}
```

```json-decision-card
{_json_block(decision_card)}
```"""


def _format_opportunity_context(context: object, output_language: str) -> str:
    if not isinstance(context, dict) or not context:
        return ""
    trigger = context.get("trigger") or context.get("source") or "opportunity_radar"
    theme_name = context.get("theme_name") or context.get("theme_id") or "unknown"
    candidate_type = context.get("candidate_type") or "unknown"
    backtest = (
        context.get("backtest_summary")
        if isinstance(context.get("backtest_summary"), dict)
        else {}
    )
    sample_size = backtest.get("sample_size") if isinstance(backtest, dict) else None
    holding_periods = (
        backtest.get("holding_periods") if isinstance(backtest, dict) else None
    )
    if sample_size:
        historical = f"Historical signal sample size: {sample_size}; holding-period metrics: {holding_periods}."
    else:
        historical = "Historical validation is unavailable or sample size is insufficient. Do not invent win rate or returns."
    if output_language == "cn":
        return (
            "Opportunity Radar context:\n"
            f"- 机会来源: {trigger}\n"
            f"- 主题: {theme_name}\n"
            f"- 候选类型: {candidate_type}\n"
            f"- 历史验证: {historical}\n"
            "Use this only as upstream evidence. The DecisionCard remains your final ruling."
        )
    return (
        "Opportunity Radar context:\n"
        f"- Trigger: {trigger}\n"
        f"- Theme: {theme_name}\n"
        f"- Candidate type: {candidate_type}\n"
        f"- Validation: {historical}\n"
        "Use this only as upstream evidence. The DecisionCard remains your final ruling."
    )


class PortfolioManager(DivergeAgentNode):
    name = "portfolio_manager"

    def build_call(self, state) -> AgentCallSpec:
        instrument_context = build_instrument_context(state["company_of_interest"])

        history = state["risk_debate_state"]["history"]
        risk_debate_state = state["risk_debate_state"]
        market_research_report = state["market_report"]
        news_report = state["news_report"]
        fundamentals_report = state["fundamentals_report"]
        sentiment_report = state["sentiment_report"]
        trader_plan = state["investment_plan"]
        output_language = state.get("output_language", "en")
        language_instruction = get_language_instruction(output_language)
        style_instruction = get_research_note_style_instruction(output_language)
        trade_feedback_message = get_trade_feedback_message(state)
        evidence_rules_instruction = get_evidence_rules_instruction()
        portfolio_context = (state.get("portfolio_context") or "").strip()
        portfolio_context_block = (
            portfolio_context
            if portfolio_context
            else _empty_portfolio_context(output_language)
        )
        opportunity_context_block = _format_opportunity_context(
            state.get("opportunity_context"), output_language
        )

        curr_situation = (
            f"{market_research_report}\n\n{sentiment_report}\n\n"
            f"{news_report}\n\n{fundamentals_report}"
        )
        past_memories = self.memory.get_memories(curr_situation, n_matches=2)

        past_memory_str = ""
        if past_memories:
            for rec in past_memories:
                past_memory_str += rec["recommendation"] + "\n\n"
        else:
            past_memory_str = "No past memories found."

        prompt = f"""As the Portfolio Manager, synthesize the risk analysts' debate and deliver the final trading decision.

Final decision authority: you are the only agent allowed to issue the user-facing portfolio rating and action. Treat upstream `signal` values as legacy directional inputs, not final verdicts. Base the final DecisionCard on evidence quality, portfolio context, risk budget, and data limitations.

{evidence_rules_instruction}

{instrument_context}

{portfolio_context_block}

{opportunity_context_block}

Guidelines for Decision-Making:
1. **Summarize Key Arguments**: Extract the strongest points from each analyst, focusing on relevance to the context.
2. **Provide Rationale**: Support your recommendation with direct evidence and counterarguments from the debate.
3. **Refine the Trader's Plan**: Start with the trader's original plan, **{trader_plan}**, and adjust it based on the analysts' insights.
4. **Learn from Past Mistakes**: Use lessons from **{past_memory_str}** to address prior misjudgments and improve the decision you are making now.
5. **Use Portfolio Context Carefully**: If portfolio context is provided, you may use it to calibrate the final rating/action and narrative. For the structured DecisionCard intelligence fields, do not assume or disclose user-specific current exposure. Position guidance must be generic, risk-based, and suitable for a user who may have no recorded position.
6. **Use Opportunity Context Safely**: If Opportunity Radar context is provided, cite only its explicit trigger, theme, candidate type, and historical validation fields. If historical validation is unavailable or sample size is insufficient, state that clearly and do not invent win rates or returns.
7. **Keep Internal Context Private**: Use the portfolio context only to adjust exposure-aware advice. Do not quote raw ledger lines, account names, JSON/code-fence names, prompt labels, or internal implementation terms in user-facing prose. For Chinese output, describe this naturally as "持仓参考" or "现有持仓".

---

**Rating Scale** (use exactly one):
- **Buy**: Strong conviction to enter or add to position
- **Overweight**: Favorable outlook, gradually increase exposure
- **Hold**: Maintain current position, no action needed
- **Underweight**: Reduce exposure, take partial profits
- **Sell**: Exit position or avoid entry

**Context:**
- Trader's proposed plan: **{trader_plan}**
- Lessons from past decisions: **{past_memory_str}**
{trade_feedback_message}

**Required Output Structure:**
1. **Rating**: State one of Buy / Overweight / Hold / Underweight / Sell.
2. **Executive Summary**: A concise action plan covering entry strategy, position sizing, key risk levels, and time horizon.
3. **Investment Thesis**: Detailed reasoning anchored in the analysts' debate and past reflections.

---

**Risk Analysts Debate History:**
{history}

---

Be decisive and ground every conclusion in specific evidence from the analysts.

Return only the structured response requested by the runtime schema:
- `decision_report`: user-facing markdown narrative without JSON code fences.
- `decision_card`: the structured final decision object.

For `decision_card`, use English enum literals exactly:
- rating: BUY, OVERWEIGHT, HOLD, UNDERWEIGHT, SELL
- action: OPEN, ADD, MAINTAIN, TRIM, EXIT, WATCH, NO_ACTION, AVOID
- confidence: high, medium, low
- trade_readiness: READY, WAITING_FOR_TRIGGER, BLOCKED_BY_RISK, DATA_INSUFFICIENT, NO_ACTION_REQUIRED
- data_quality_level: complete, partial, weak, insufficient

Do not invent exact price levels if the reports do not provide reliable current price or technical levels. If price levels are unavailable, use null and explain the limitation in data_quality_notes. Rating and action are different concepts. Conviction_score reflects opportunity, risk, evidence strength, and data quality. Key_reasons must cite concrete evidence from analyst reports.
Do not generate Portfolio Fit, Decision Journal, Opportunity Queue, or Conviction Breakdown fields. Do not write phrases such as "your current position", "your portfolio", "你当前仓位", or "你的组合" inside `position_guidance`; keep it generic and risk-based.

{style_instruction}
{language_instruction}"""

        runtime_warnings = list(state.get("runtime_warnings") or [])
        return AgentCallSpec(
            prompt=AdkPrompt(system_message=prompt),
            output_schema=PortfolioManagerStructuredOutput,
            output_key="portfolio_decision_structured",
            metadata={
                "instrument_context": instrument_context,
                "risk_debate_state": risk_debate_state,
                "runtime_warnings": runtime_warnings,
            },
        )

    def apply_response(self, state, spec, response) -> dict:
        runtime_warnings = list(spec.metadata["runtime_warnings"])
        try:
            structured = parse_structured_output(
                response.content,
                PortfolioManagerStructuredOutput,
            )
        except Exception as exc:
            runtime_warnings.append(_format_structured_output_warning(exc))
            return self._build_result(
                spec=spec,
                response_content=response.content,
                runtime_warnings=runtime_warnings,
            )

        decision_card = structured.decision_card.model_dump(mode="json")
        structured_payload = structured.model_dump(mode="json")
        return self._build_result(
            spec=spec,
            response_content=_render_structured_portfolio_decision(structured),
            runtime_warnings=runtime_warnings,
            portfolio_decision_card=decision_card,
            portfolio_decision_structured=structured_payload,
        )

    def handle_call_error(self, state, spec, error: Exception) -> dict | None:
        if not _is_transient_llm_error(error):
            return None

        logger.exception(
            "Portfolio Manager LLM failed with a transient error; using fallback final decision."
        )
        runtime_warnings = list(spec.metadata["runtime_warnings"])
        runtime_warnings.append(_format_transient_llm_warning(error))
        portfolio_decision_card = _build_fallback_portfolio_decision_card(error)
        return self._build_result(
            spec=spec,
            response_content=_build_fallback_portfolio_decision(
                instrument_context=spec.metadata["instrument_context"],
                error=error,
            ),
            runtime_warnings=runtime_warnings,
            portfolio_decision_card=portfolio_decision_card,
        )

    def _build_result(
        self,
        *,
        spec: AgentCallSpec,
        response_content: str,
        runtime_warnings: list[dict],
        portfolio_decision_card: dict | None = None,
        portfolio_decision_structured: dict | None = None,
    ) -> dict:
        risk_debate_state = spec.metadata["risk_debate_state"]
        new_risk_debate_state = {
            "judge_decision": response_content,
            "history": risk_debate_state["history"],
            "aggressive_history": risk_debate_state["aggressive_history"],
            "conservative_history": risk_debate_state["conservative_history"],
            "neutral_history": risk_debate_state["neutral_history"],
            "latest_speaker": "Judge",
            "current_aggressive_response": risk_debate_state[
                "current_aggressive_response"
            ],
            "current_conservative_response": risk_debate_state[
                "current_conservative_response"
            ],
            "current_neutral_response": risk_debate_state["current_neutral_response"],
            "count": risk_debate_state["count"],
        }

        result = {
            "risk_debate_state": new_risk_debate_state,
            "final_trade_decision": response_content,
            "runtime_warnings": runtime_warnings,
        }
        if portfolio_decision_card is not None:
            result["portfolio_decision_card"] = portfolio_decision_card
        if portfolio_decision_structured is not None:
            result["portfolio_decision_structured"] = portfolio_decision_structured
        return result
