import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

const componentPath = path.join(import.meta.dirname, "ScreenerDashboard.tsx");

test("ScreenerDashboard provides a stable screener workspace destination", () => {
  const source = readFileSync(componentPath, "utf8");

  assert.match(source, /from "@\/components\/ui\/button"/);
  assert.match(source, /from "@\/components\/ui\/card"/);
  assert.match(source, /from "@\/components\/ui\/input"/);
  assert.match(source, /from "@\/components\/ui\/select"/);
  assert.match(source, /usePreferences/);
  assert.match(source, /useSearchParams/);
  assert.match(source, /SlidersHorizontal/);
  assert.match(source, /<Button/);
  assert.match(source, /<Input/);
  assert.match(source, /<Select/);
  assert.match(source, /getScreenerConfigOptions/);
  assert.match(source, /createScreenerTask/);
  assert.match(source, /listScreenerPresets/);
  assert.match(source, /replaceScreenerPresets/);
  assert.match(source, /SAVED_SCREENER_BARS_KEY/);
  assert.match(source, /LAST_SCREENER_BAR_KEY/);
  assert.match(source, /FALLBACK_FILTER_PRESET_SELECTIONS/);
  assert.match(source, /ma20_position:\s*"price_above_ma20"/);
  assert.match(source, /readLastScreenerBar/);
  assert.match(source, /writeLastScreenerBar/);
  assert.match(source, /createFormStateFromPayload/);
  assert.match(source, /fingerprintScreenerPayload/);
  assert.match(source, /\[presetName,\s*setPresetName\]/);
  assert.match(source, /Preset Name/);
  assert.match(source, /Name this screen/);
  assert.match(source, /const name = presetName\.trim\(\) \|\| fallbackName/);
  assert.match(source, /setPresetName\(savedBar\.name\)/);
  assert.match(source, /savedBarFromPresetRecord/);
  assert.match(source, /records\.map\(savedBarFromPresetRecord\)/);
  assert.match(source, /buildActivityHref/);
  assert.match(source, /buildScreenerHref/);
  assert.match(source, /buildScreenerTaskHref/);
  assert.doesNotMatch(source, /buildScreenerRunHref/);
  assert.match(source, /const selectedRunId = searchParams\.get\("runId"\)/);
  assert.match(source, /screenerRuns/);
  assert.match(source, /\[hideLatestRun,\s*setHideLatestRun\]/);
  assert.match(source, /const latestScreenerRunId = useMemo/);
  assert.match(source, /snapshot_available !== false/);
  assert.match(source, /const displayedRunId = selectedRunId \?\? \(hideLatestRun \? null : latestScreenerRunId\)/);
  assert.match(source, /\[resultStale,\s*setResultStale\]/);
  assert.match(source, /const markResultStale = \(\) => \{/);
  assert.match(source, /setResultStale\(true\)/);
  assert.match(source, /const dismissSelectedRun = \(\) => \{/);
  assert.match(source, /router\.replace\(buildScreenerHref\(\), \{ scroll: false \}\)/);
  assert.match(source, /displayedRunId && resultStale/);
  assert.match(source, /screenerDashboard\.staleResultTitle/);
  assert.match(source, /screenerDashboard\.staleResultBody/);
  assert.match(source, /screenerDashboard\.staleResultDismiss/);
  assert.match(source, /<ScreenerResultsViewer runId=\{displayedRunId\} embedded \/>/);
  assert.match(source, /<ScreenerResultPlaceholder/);
  assert.match(source, /activeTaskId=\{firstActiveScreenerTask\?\.id \?\? null\}/);
  assert.match(source, /function ScreenerResultPlaceholder/);
  assert.match(source, /screenerDashboard\.resultSlot/);
  assert.match(source, /screenerDashboard\.placeholderReadyTitle/);
  assert.match(source, /screenerDashboard\.placeholderRunningTitle/);
  assert.match(source, /function PlaceholderMetric/);
  assert.match(source, /CONTROL_INPUT_CLASS/);
  assert.match(source, /COMPACT_SELECT_CLASS/);
  assert.match(source, /card-surface/);
  assert.match(source, /viewer-frame/);
  assert.doesNotMatch(source, /clearSelectedRun/);
  assert.doesNotMatch(source, /t\("screenerDashboard\.recentRuns", "Recent Runs"\)/);
  assert.doesNotMatch(source, /t\("screenerDashboard\.metadataOnly", "Metadata only"\)/);
  assert.doesNotMatch(source, /Market Coverage/);
  assert.doesNotMatch(source, /Candidate Cache/);
  assert.doesNotMatch(source, /Avg Hold Days/);
  assert.doesNotMatch(source, /screenerDashboard\.newScreener/);
  assert.doesNotMatch(source, /screenerDashboard\.guide/);
  assert.doesNotMatch(source, /Preset Library/);
  assert.doesNotMatch(source, /Filter Conditions/);
  assert.doesNotMatch(source, /Candidate Preview/);
  assert.doesNotMatch(source, /presetRows/);
  assert.doesNotMatch(source, /previewRows/);
  assert.doesNotMatch(source, /filterGroups/);
  assert.match(source, /Ranking Model/);
  assert.match(source, /Top K/);
  assert.doesNotMatch(source, /Signal/);
  assert.doesNotMatch(source, /None \(all stocks\)/);
  assert.doesNotMatch(source, /signalValue/);
  assert.match(source, /SPECIFIC_BREAKOUT_PATTERNS/);
  assert.match(source, /filterPresetSelections\.pattern/);
  assert.match(source, /selectedPattern && SPECIFIC_BREAKOUT_PATTERNS\.has\(selectedPattern\)/);
  assert.match(source, /filterTabs/);
  assert.match(source, /\[isConfigCollapsed,\s*setIsConfigCollapsed\]/);
  assert.match(source, /buildSelectedFilterSummaries/);
  assert.match(source, /selectedRankingProfileLabel/);
  assert.match(source, /visibleSelectedFilterSummaries/);
  assert.match(source, /screenerDashboard\.configPanel/);
  assert.match(source, /screenerDashboard\.collapseConfig/);
  assert.match(source, /screenerDashboard\.expandConfig/);
  assert.match(source, /screenerDashboard\.noConfigFilters/);
  assert.match(source, /aria-expanded=\{!isConfigCollapsed\}/);
  assert.match(source, /className="screener-config-panel viewer-frame"/);
  assert.match(source, /className="screener-config-summary/);
  assert.match(source, /Technical/);
  assert.match(source, /Pattern/);
  assert.match(source, /Fundamental/);
  assert.match(source, /FILTER_GROUP_CATEGORY/);
  assert.match(source, /rsi:\s*"technical"/);
  assert.match(source, /ma20_position:\s*"technical"/);
  assert.match(source, /ma60_position:\s*"technical"/);
  assert.match(source, /ma_alignment:\s*"technical"/);
  assert.match(source, /ret_20:\s*"technical"/);
  assert.match(source, /ret_60:\s*"technical"/);
  assert.doesNotMatch(source, /moving_average:\s*"technical"/);
  assert.doesNotMatch(source, /performance:\s*"technical"/);
  assert.match(source, /pattern:\s*"pattern"/);
  assert.match(source, /volume:\s*"pattern"/);
  assert.match(source, /pe_ttm:\s*"fundamental"/);
  assert.match(source, /ps_ttm:\s*"fundamental"/);
  assert.match(source, /pb:\s*"fundamental"/);
  assert.match(source, /peg:\s*"fundamental"/);
  assert.doesNotMatch(source, /valuation:\s*"fundamental"/);
  assert.match(source, /roe:\s*"fundamental"/);
  assert.match(source, /gross_margin:\s*"fundamental"/);
  assert.match(source, /net_margin:\s*"fundamental"/);
  assert.match(source, /revenue_growth_yoy:\s*"fundamental"/);
  assert.match(source, /net_income_growth_yoy:\s*"fundamental"/);
  assert.match(source, /current_ratio:\s*"fundamental"/);
  assert.match(source, /debt_to_assets:\s*"fundamental"/);
  assert.doesNotMatch(source, /quality:\s*"fundamental"/);
  assert.doesNotMatch(source, /growth:\s*"fundamental"/);
  assert.doesNotMatch(source, /balance_sheet:\s*"fundamental"/);
  assert.match(source, /LEGACY_FILTER_OPTION_GROUPS/);
  assert.match(source, /activeFilterTab/);
  assert.match(source, /visibleFilterGroups/);
  assert.match(source, /selectedFilterCount/);
  assert.match(source, /\{selectedFilterCount\} selected/);
  assert.match(source, /<Select\s+value=\{/);
  assert.match(source, /onValueChange=\{\(value\) => updateFilterPreset\(group\.id, value\)\}/);
  assert.match(source, /<SelectTrigger/);
  assert.match(source, /<SelectItem key=\{option\.value\} value=\{option\.value\}>/);
  assert.doesNotMatch(source, /onClick=\{\(\) => updateFilterPreset\(group\.id, option\.value\)\}/);
  assert.match(source, /FUNDAMENTAL_FILTER_GROUPS/);
  assert.match(source, /include_fundamentals/);
  assert.match(source, /filter_preset_groups/);
  assert.doesNotMatch(source, /Overview/);
  assert.doesNotMatch(source, /ETF/);
  assert.doesNotMatch(source, /Snapshot/);
  assert.doesNotMatch(source, /Stats/);
  assert.match(source, /Save/);
  assert.match(source, /Run/);
  assert.doesNotMatch(source, /openScreenerDialog/);
  assert.match(source, /TOP_K_LIMIT = 100/);
  assert.doesNotMatch(source, /formatRunDate\(run\.as_of_date, locale\)/);
  assert.doesNotMatch(source, /buildScreenerRunListKey\(run, index\)/);
  assert.doesNotMatch(source, /key=\{run\.id\}/);
});

test("ScreenerDashboard uses the shared responsive workbench width frame", () => {
  const source = readFileSync(componentPath, "utf8");

  assert.match(source, /className="workbench-content-frame space-y-6"/);
  assert.doesNotMatch(source, /max-w-6xl/);
});

test("ScreenerDashboard follows the shared theme tokens instead of a local color palette", () => {
  const source = readFileSync(componentPath, "utf8");

  assert.doesNotMatch(source, /#[0-9A-Fa-f]{3,8}/);
  assert.doesNotMatch(source, /bg-\[#/);
  assert.doesNotMatch(source, /border-\[#/);
  assert.doesNotMatch(source, /text-\[#/);
  assert.doesNotMatch(source, /#f4e3cd|#f9ead4|#dcc5a7/);
  assert.match(source, /var\(--surface-strong\)/);
  assert.match(source, /var\(--border-strong\)/);
  assert.match(source, /var\(--primary\)/);
});

test("ScreenerDashboard does not expose result ownership labels", () => {
  const source = readFileSync(componentPath, "utf8");

  assert.doesNotMatch(source, /getScreenerRunScopeLabel/);
  assert.doesNotMatch(source, /screenerDashboard\.scope\.mine/);
  assert.doesNotMatch(source, /screenerDashboard\.scope\.team/);
  assert.doesNotMatch(source, /screenerDashboard\.scope\.workspace/);
});

test("ScreenerDashboard navigates to task progress before refreshing workspace lists", () => {
  const source = readFileSync(componentPath, "utf8");
  const runCurrentBarSource = source.slice(
    source.indexOf("const runCurrentBar = async"),
    source.indexOf("const controlsDisabled")
  );
  const pushIndex = runCurrentBarSource.indexOf("router.push(buildScreenerTaskHref(response.task_id))");
  const refreshTasksIndex = runCurrentBarSource.indexOf("void refreshScreenerTasks()");
  const refreshRunsIndex = runCurrentBarSource.indexOf("void refreshScreenerRuns()");

  assert.match(runCurrentBarSource, /let didNavigate = false/);
  assert.match(runCurrentBarSource, /if \(!didNavigate\) \{\s*setRunning\(false\);/);
  assert.ok(pushIndex > -1, "expected run flow to push the task route");
  assert.ok(refreshTasksIndex > -1, "expected run flow to refresh tasks");
  assert.ok(refreshRunsIndex > -1, "expected run flow to refresh runs");
  assert.ok(pushIndex < refreshTasksIndex, "task route push should happen before task refresh");
  assert.ok(pushIndex < refreshRunsIndex, "task route push should happen before run refresh");
});
