import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

const taskProgressPath = path.join(import.meta.dirname, "TaskProgress.tsx");

test("TaskProgress subscribes to backend task snapshots and renders the six-stage pipeline", () => {
  const source = readFileSync(taskProgressPath, "utf8");

  assert.match(source, /from "@\/components\/ui\/badge"/);
  assert.match(source, /from "@\/components\/ui\/button"/);
  assert.match(source, /from "@\/components\/ui\/card"/);
  assert.match(source, /from "@\/components\/ui\/input"/);
  assert.match(source, /from "@\/components\/ui\/scroll-area"/);
  assert.match(source, /from "@\/components\/ui\/select"/);
  assert.match(source, /<Card/);
  assert.match(source, /<Button/);
  assert.match(source, /<Badge/);
  assert.match(source, /<Input/);
  assert.match(source, /<Select/);
  assert.match(source, /<ScrollArea/);
  assert.doesNotMatch(source, /<input/);
  assert.doesNotMatch(source, /<select/);
  assert.match(source, /subscribeToTask/);
  assert.match(source, /getTask/);
  assert.match(source, /cancelTask/);
  assert.match(source, /onTaskCompleteRef/);
  assert.match(source, /hasNotifiedTaskCompleteRef/);
  assert.match(source, /const syncAndSubscribe = async/);
  assert.match(source, /if \(!nextTask \|\| isTerminalTaskStatus\(nextTask\.status\)\) \{\s*return;\s*\}/s);
  assert.match(source, /unsubscribe\?\.\(\);\s*unsubscribe = undefined;\s*void syncTask\(\);/s);
  assert.match(source, /\}, \[taskId, t\]\)/);
  assert.doesNotMatch(source, /\}, \[onTaskComplete, taskId, t\]\)/);
  assert.match(source, /waiting_for_quota/);
  assert.match(source, /queue_position/);
  assert.match(source, /blocked_vendor/);
  assert.match(source, /TaskQueueNotice/);
  assert.match(source, /task\.cancel/);
  assert.match(source, /not_started/);
  assert.match(source, /processing/);
  assert.match(source, /completed/);
  assert.match(source, /Analysts/);
  assert.match(source, /Research/);
  assert.match(source, /Trading/);
  assert.match(source, /Risk/);
  assert.match(source, /Portfolio/);
  assert.match(source, /Summary/);
  assert.match(source, /View Report/);
  assert.match(source, /Request details for/);
  assert.match(source, /analysis_date/);
  assert.match(source, /RESEARCH_DEPTH_LABELS/);
  assert.match(source, /Shallow/);
  assert.match(source, /Medium/);
  assert.match(source, /Deep/);
  assert.match(source, /quick_think_llm/);
  assert.match(source, /deep_think_llm/);
  assert.match(source, /readOnly/);
  assert.match(source, /scale-y-\[-1\]/);
  assert.doesNotMatch(source, /research_depth:\s*String\(request\.research_depth\)/);
  assert.doesNotMatch(source, /openai_reasoning_effort/);
  assert.doesNotMatch(source, /google_thinking_level/);
  assert.equal(source.includes("max-w-5xl"), false);
  assert.match(source, /workbench-content-frame space-y-6/);
  assert.match(source, /task-event-item/);
  assert.doesNotMatch(source, /\.filter\(\(event\) => event\.message\)/);
  assert.match(source, /describeProgressEvent\(event, t\)/);
  assert.match(source, /task\.progress\.agentStatus/);
});
