import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

const componentPath = path.join(import.meta.dirname, "WorkspaceAccountMenu.tsx");

test("WorkspaceAccountMenu exposes a compact utility bar for the shell overlay", () => {
  const source = readFileSync(componentPath, "utf8");

  assert.match(source, /from "@\/components\/ui\/button"/);
  assert.match(source, /from "@\/components\/ui\/dropdown-menu"/);
  assert.match(source, /from "@\/components\/ui\/select"/);
  assert.match(source, /<Button/);
  assert.match(source, /<Select/);
  assert.match(source, /DropdownMenuContent/);
  assert.match(source, /SelectTrigger/);
  assert.match(source, /authEnabled:\s*boolean/);
  assert.match(source, /authUser:\s*AuthUser \| null/);
  assert.match(source, /canManageUsers:\s*boolean/);
  assert.match(source, /onLogout:\s*\(\)\s*=>\s*void/);
  assert.match(source, /loggingOut:\s*boolean/);
  assert.match(source, /selectedOutputLanguage:\s*string \| null/);
  assert.match(source, /onOutputLanguageChange:\s*\(value:\s*string\)/);
  assert.match(source, /className="workbench-account-menu pointer-events-auto relative z-\[40\] ml-auto flex shrink-0 items-center gap-2"/);
  assert.match(source, /pointer-events-auto/);
  assert.match(source, /inline-flex items-center gap-1\.5 rounded-full/);
  assert.match(source, /h-8 w-8/);
  assert.doesNotMatch(source, /max-w-\[1600px\]/);
  assert.doesNotMatch(source, /fixed right-4 top-4 z-\[55\]/);
  assert.match(source, /Interface Preferences/);
  assert.match(source, /Visual Style/);
  assert.match(source, /\(\["light", "dark", "proof", "everforest"\] as const\)/);
  assert.match(source, /setVisualStyle/);
  assert.match(source, /Output Language/);
  assert.match(source, /onValueChange=\{onOutputLanguageChange\}/);
  assert.match(source, /data-active=\{theme === themeValue\}/);
  assert.match(source, /data-active=\{language === languageValue\}/);
  assert.match(source, /data-active=\{visualStyle === styleValue\}/);
  assert.match(source, /\(\["normal", "stylful"\] as const\)/);
  assert.match(source, /t\("workspace\.resetRequired", "Reset required"\)/);
  assert.match(source, /t\("common\.settings", "Settings"\)/);
  assert.match(source, /"sidebar\.outputLanguageHint"/);
  assert.match(source, /`analysis\.outputLanguage\.\$\{languageOption\.value\}`/);
  assert.doesNotMatch(source, /bg-\[rgba\(255,253,248/);
  assert.doesNotMatch(source, /border-\[rgba\(150,118,99/);
  assert.match(source, /getConfigOptions/);
  assert.match(source, /Workspace Access/);
  assert.match(source, /Admin Console/);
  assert.doesNotMatch(source, /workspace\.dataSources/);
  assert.doesNotMatch(source, /href="\/admin\/data-sources"/);
  assert.match(source, /flex flex-wrap justify-end gap-2/);
  assert.match(source, /Sign Out/);
  assert.match(source, /Open Workspace/);
  assert.match(source, /must_change_password/);
  assert.match(source, /event\.key === "Escape"/);
  assert.match(source, /pointerdown/);
  assert.match(source, /onOpenSidebar\?: \(\) => void/);
  assert.match(source, /aria-label=\{t\("common\.menu", "Menu"\)\}/);
  assert.match(source, /md:hidden/);
  assert.doesNotMatch(source, /<button/);
  assert.doesNotMatch(source, /<select/);
  assert.doesNotMatch(source, /px-4 pt-4 md:px-6/);
  assert.doesNotMatch(source, /<header className="pointer-events-auto/);

  const accountIndex = source.indexOf("DropdownMenu");
  const settingsIndex = source.indexOf("Interface Preferences");
  assert.notEqual(accountIndex, -1);
  assert.notEqual(settingsIndex, -1);
  assert.ok(accountIndex < settingsIndex, "account trigger should render before settings");
  assert.doesNotMatch(source, /Research Suite/);
  assert.doesNotMatch(source, /Workspace controls and session access/);
  assert.match(source, /DropdownMenuTrigger asChild/);
  assert.match(source, /grid h-8 w-8 place-items-center/);
  assert.match(source, /size-10 rounded-full/);
});
