from typing import Annotated

from typing_extensions import NotRequired, TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(TypedDict):
    messages: Annotated[list[object], "Conversation messages exchanged by agents"]
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    output_language: Annotated[str, "Output language code: en or cn"]
    earnings_event: NotRequired[
        Annotated[dict[str, object] | None, "Optional earnings event context"]
    ]
    instrument_type: NotRequired[
        Annotated[
            str | None, "Normalized instrument classification for valuation logic"
        ]
    ]
    valuation_applicability: NotRequired[
        Annotated[str | None, "Whether operating-company DCF is applicable"]
    ]
    valuation_applicability_reason: NotRequired[
        Annotated[str | None, "Reason why DCF is or is not applicable"]
    ]
    historical_trade_feedback: NotRequired[
        Annotated[str | None, "Ticker-matched historical trade review prompt block"]
    ]
    historical_trade_reviews: NotRequired[
        Annotated[
            list[dict[str, object]], "Structured historical trade review payloads"
        ]
    ]
    portfolio_context: NotRequired[
        Annotated[str | None, "Current owner-scoped holdings and exposure summary"]
    ]
    opportunity_context: NotRequired[
        Annotated[
            dict[str, object] | None, "Structured opportunity radar trigger context"
        ]
    ]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    runtime_warnings: NotRequired[
        Annotated[list[dict[str, str]], "Non-fatal runtime warnings surfaced to users"]
    ]
    report_summary: NotRequired[
        Annotated[str, "Concise Summary Agent output for the complete report"]
    ]
